### ISSUE TITLE
[Bug] Crash on world load (1.19.2, Fabric)

### ISSUE THREAD

**Issue by TheRealIceCracker** [Hunter19823/kubejsadditions#4]
Game loads to main menu fine but crashes when loading a world.

Crash log pastebin: [https://pastebin.com/VR94cBh1](https://pastebin.com/VR94cBh1)
Minecraft 1.19.2
Fabric 0.14.21
Rhino 1902.2.2 build 268
Architectury API 6.5.85
KubeJS 1902.2.4 build 26
KubeJS Additions 3.0.4

**Comment by AwesomeDude091** [comment]
Can confirm

**Comment by Hunter19823** [comment]
I’m currently working on resolving this issue.
It was due to a mix of both Fabric API being out of date and KubeJS 6.1 containing breaking changes.
My hope is to resolve this sometime this week.

**Comment by Hunter19823** [comment]
This should now be fixed in version 3.1.1.
